# This is an example of my work conducted during my tenure at CEFIR

In [1]:
import os
import pandas as pd
import datetime
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
import statsmodels.api as sm
import statsmodels.tsa.stattools as tsa


#import warnings
#warnings.filterwarnings('ignore')


mpl.rcParams['figure.figsize'] = (10, 6)
mpl.rcParams['figure.dpi'] = 150

/Users/nvarioshkin/opt/anaconda3/lib/python3.8/site-packages/statsmodels/tsa/base/tsa_model.py:7: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import (to_datetime, Int64Index, DatetimeIndex, Period,
/Users/nvarioshkin/opt/anaconda3/lib/python3.8/site-packages/statsmodels/tsa/base/tsa_model.py:7: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import (to_datetime, Int64Index, DatetimeIndex, Period,

In [2]:
pd.options.display.max_rows = 150

In [467]:
os.chdir('/Users/nvarioshkin/Desktop/RA Petrova/Task 1')
os.listdir()

['charts.do',
 '.DS_Store',
 'charts_data.dta',
 'europe.pdf',
 'usa.pdf',
 'chart examples.docx',
 'automation per thous workers.xlsx',
 'README.txt',
 '.ipynb_checkpoints']

In [468]:
data = pd.read_excel('automation per thous workers.xlsx', usecols = 'A:AB')
data.drop(['market'], axis = 1, inplace = True)
data.dropna(axis = 0, how = 'any', subset = ['country', 'industry'], inplace = True)

In [6]:
data

,country,industry,1993,1994,1995,1996,1997,1998,1999,2000,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,USA,000-All Industries,43454.0,49130.0,56945.0,60965.0,66394.0,70466.0,79959.0,89880.0,...,168489.0,166183.0,173174.0,184679.0,197962.0,215817.0,236891.0,260642.0,285143.0,307135.0
1,USA,"A-B-Agriculture, forestry, fishing",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.0,11.0,12.0,28.0,55.0,71.0,80.0,99.0,105.0,129.0
2,USA,C-Mining and quarrying,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,2.0,2.0,2.0,2.0,6.0,39.0,41.0,46.0,51.0
3,USA,D-Manufacturing,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,76968.0,84080.0,96826.0,118127.0,142152.0,167943.0,197722.0,232036.0,256177.0,277141.0
4,USA,10-12-Food and beverages,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3502.0,4132.0,5067.0,6060.0,6948.0,8386.0,9647.0,10928.0,11735.0,13082.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
464,UK,"E-Electricity, gas, water supply",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,46.0,46.0,46.0,57.0,61.0,62.0,44.0,45.0,46.0,46.0
465,UK,F-Construction,0.0,8.0,8.0,8.0,8.0,18.0,24.0,26.0,...,88.0,91.0,83.0,86.0,85.0,78.0,58.0,60.0,58.0,68.0
466,UK,P-Education/research/development,0.0,90.0,108.0,148.0,185.0,223.0,262.0,292.0,...,264.0,241.0,226.0,196.0,186.0,217.0,213.0,193.0,213.0,221.0
467,UK,90-All other non-manufacturing branches,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,45.0,45.0,51.0,59.0,60.0,60.0,65.0,68.0
468,UK,99-Unspecified,213.0,304.0,354.0,384.0,439.0,508.0,498.0,569.0,...,794.0,862.0,949.0,1092.0,1097.0,1151.0,1408.0,1688.0,1974.0,2256.0

In [7]:
short = ['     A-B-Agriculture, forestry, fishing', '     C-Mining and quarrying', '          10-12-Food and beverages', 
        '          13-15-Textiles', '          16-Wood and furniture', '          17-18-Paper', '          19-22-Plastic and chemical products', 
        '          23-Glass, ceramics, stone, mineral products (non-auto', '          24-28-Metal', '          26-27-Electrical/electronics', '          29-Automotive', '          30-Other vehicles', '          91-All other manufacturing branches', '     E-Electricity, gas, water supply', '     F-Construction', '     P-Education/research/development', '     90-All other non-manufacturing branches', '     99-Unspecified']

In [8]:
short

['     A-B-Agriculture, forestry, fishing',
 '     C-Mining and quarrying',
 '          10-12-Food and beverages',
 '          13-15-Textiles',
 '          16-Wood and furniture',
 '          17-18-Paper',
 '          19-22-Plastic and chemical products',
 '          23-Glass, ceramics, stone, mineral products (non-auto',
 '          24-28-Metal',
 '          26-27-Electrical/electronics',
 '          29-Automotive',
 '          30-Other vehicles',
 '          91-All other manufacturing branches',
 '     E-Electricity, gas, water supply',
 '     F-Construction',
 '     P-Education/research/development',
 '     90-All other non-manufacturing branches',
 '     99-Unspecified']

In [9]:
df = data.set_index(keys = ['country', 'industry']).stack().reset_index()
df.columns = ['country', 'industry', 'year', 'robots']
df = df[df['industry'].isin(short)]
df['industry'] = df['industry'].str.strip(' ')

In [10]:
df

      country                            industry  year  robots
25        USA  A-B-Agriculture, forestry, fishing  1993     0.0
26        USA  A-B-Agriculture, forestry, fishing  1994     0.0
27        USA  A-B-Agriculture, forestry, fishing  1995     0.0
28        USA  A-B-Agriculture, forestry, fishing  1996     0.0
29        USA  A-B-Agriculture, forestry, fishing  1997     0.0
...       ...                                 ...   ...     ...
11245      UK                      99-Unspecified  2013  1151.0
11246      UK                      99-Unspecified  2014  1408.0
11247      UK                      99-Unspecified  2015  1688.0
11248      UK                      99-Unspecified  2016  1974.0
11249      UK                      99-Unspecified  2017  2256.0

[4500 rows x 4 columns]

In [14]:
df_usa = df[df['country'] == 'USA'].reset_index(drop = True)
df_other = df[df['country'] != 'USA'].reset_index(drop = True)

df_europe = df_other.groupby(by = ['industry', 'year'], as_index = False).sum()
df_europe.insert(0, 'country', 'Europe')

df_short = pd.concat([df_usa, (df_europe)])
df_short.reset_index(drop = True, inplace = True)

df_short['industry'] = df_short['industry'].str.rpartition(sep = '-')[2]

df_short.loc[df_short['industry'] == 'auto', 'industry'] = 'Glass, ceramics, stone, mineral products'
df_short.loc[df_short['industry'] == 'manufacturing branches', 'industry'] = 'All other non-manufacturing branches'

In [15]:
df_short

    country                        industry  year  robots
0       USA  Agriculture, forestry, fishing  1993     0.0
1       USA  Agriculture, forestry, fishing  1994     0.0
2       USA  Agriculture, forestry, fishing  1995     0.0
3       USA  Agriculture, forestry, fishing  1996     0.0
4       USA  Agriculture, forestry, fishing  1997     0.0
..      ...                             ...   ...     ...
895  Europe  Education/research/development  2013  2765.0
896  Europe  Education/research/development  2014  2723.0
897  Europe  Education/research/development  2015  2727.0
898  Europe  Education/research/development  2016  2865.0
899  Europe  Education/research/development  2017  3008.0

[900 rows x 4 columns]

In [17]:
labels = list(df_short['industry'].unique())
labels.sort()
numbers = [1, 16, 17] + list(range(2, 15)) + [18] + [15]
map_dict = dict(zip(labels, numbers))
map_dict_rev = dict(zip(numbers, labels))


df_short['ind'] = df_short['industry'].map(map_dict)

label_dict = {'ind' : map_dict_rev}

In [19]:
df_short

    country                        industry  year  robots  ind
0       USA  Agriculture, forestry, fishing  1993     0.0    1
1       USA  Agriculture, forestry, fishing  1994     0.0    1
2       USA  Agriculture, forestry, fishing  1995     0.0    1
3       USA  Agriculture, forestry, fishing  1996     0.0    1
4       USA  Agriculture, forestry, fishing  1997     0.0    1
..      ...                             ...   ...     ...  ...
895  Europe  Education/research/development  2013  2765.0    4
896  Europe  Education/research/development  2014  2723.0    4
897  Europe  Education/research/development  2015  2727.0    4
898  Europe  Education/research/development  2016  2865.0    4
899  Europe  Education/research/development  2017  3008.0    4

[900 rows x 5 columns]

In [20]:
df_short.to_stata('short.dta', write_index = False, value_labels = label_dict)

In [3]:
os.chdir('/Users/nvarioshkin/Desktop/RA Petrova/Task 2')
os.listdir()

['Automation_data_prepare_career_values.dta',
 'tables',
 '.DS_Store',
 'Chetty_graph_regressions.do',
 'attendance.pdf',
 '~$5_kr26_table.doc',
 '_p25_kir26.pdf',
 'chetty_mobility.pdf',
 'chetty.dta',
 'chetty_aggregated_cz.dta',
 '_p25_kr26_median.pdf',
 'second.pdf',
 '_p25_kr26.pdf',
 'Automation_data_prepare_with_chetty.dta',
 '_p25_kir26_median.pdf',
 'task_2.do',
 'first.pdf',
 'career_value_graphs_v1.do']

In [4]:
data_1 = pd.read_stata('Automation_data_prepare_career_values.dta')
data_2 = pd.read_stata('chetty.dta')
data_3 = pd.read_stata('Automation_data_prepare_with_chetty.dta')

In [23]:
miss_cz_2 = list(data_1[['expof_italy_0416', 'czone']][data_1['expof_italy_0416'].isna()]['czone'].dropna())
miss_cz_2 = [int(x) for x in miss_cz_2]

In [13]:
data_1.columns

Index(['czone', 'noc_cv_tot2000', 'noc_cv_tot2004', 'noc_cv_tot2008',
       'noc_cv_tot2016', 'noc_cc2000_2004', 'noc_cc2000_2008',
       'noc_cc2004_2008', 'noc_cc2000_2016', 'noc_cc2004_2016',
       ...
       'int_sweden_coll', 'int_france_hsl', 'int_france_smcllg',
       'int_france_coll', 'int_finland_hsl', 'int_finland_smcllg',
       'int_finland_coll', 'int_euro_hsl', 'int_euro_smcllg', 'int_euro_coll'],
      dtype='object', length=1002)

In [6]:
data_2

,county,state,county_name,stateabbrv,_merge,_merge_chetty_to_vadim,cty1990,cty2000,cz_name,pct_causal_p25_kr26,...,pct_causal_p75_kir26_m,pct_causal_p25_kir26_avg,pct_causal_p75_kir26_avg,pct_pt_causal_p25_km26,pct_pt_causal_p75_km26,cz,csa,csa_name,_merge_chetty,county_state
0,Niobrara,WY,,,NaN,master only (1),NaN,NaN,,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,master only (1),"Niobrara, WY"
1,Mineral,NV,,,NaN,master only (1),NaN,NaN,,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,master only (1),"Mineral, NV"
2,Mineral,MT,,,NaN,master only (1),NaN,NaN,,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,master only (1),"Mineral, MT"
3,Graham,KS,,,NaN,master only (1),NaN,NaN,,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,master only (1),"Graham, KS"
4,Williamsburg City,VA,,,NaN,master only (1),NaN,NaN,,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,master only (1),"Williamsburg City, VA"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3135,Yukon Koyukuk,AK,Yukon-Koyukuk,AK,matched (3),matched (3),2290.0,2290.0,Fairbanks,-0.137913,...,NaN,NaN,NaN,-0.192597,-0.172013,34115.0,NaN,,matched (3),"Yukon Koyukuk, AK"
3136,Yuma,AZ,Yuma,AZ,matched (3),matched (3),4027.0,4027.0,Yuma,0.351439,...,0.081392,0.145679,-0.269957,0.264829,0.136005,38100.0,NaN,,matched (3),"Yuma, AZ"
3137,Yuma,CO,Yuma,CO,matched (3),matched (3),8125.0,8125.0,Sterling,1.476847,...,0.354429,0.735048,0.191615,0.892712,0.538896,28301.0,NaN,,matched (3),"Yuma, CO"
3138,Zapata,TX,Zapata,TX,matched (3),matched (3),48505.0,48505.0,Laredo,0.535796,...,0.227626,0.219584,0.231667,0.391422,0.288566,31503.0,NaN,,matched (3),"Zapata, TX"
3139,Zavala,TX,Zavala,TX,matched (3),matched (3),48507.0,48507.0,Crystal City,-0.083800,...,-0.247473,-0.017108,-0.846808,0.208027,0.276574,31501.0,NaN,,matched (3),"Zavala, TX"

In [7]:
miss_cz = list(data_3[data_3['chetty_match'] == 'master only (1)']['czone'])
miss_cz.sort()

In [12]:
print(*[int(x) for x in miss_cz])

26202 26204 26401 26404 26405 26804 27003 27010 27012 27603 27604 28303 28601 28606 29002 30605 30906 30907 31304 32303 32603 34101 34104 34114 34306 34309 34604 34804 35905 37902 39204

In [27]:
set(miss_cz) & set(miss_cz_2)

{34101, 34104, 34114}

In [90]:
os.chdir('/Users/nvarioshkin/Desktop/RA Petrova/Task 4')
os.listdir()

['.DS_Store',
 'dc-decomp-infadj-allcz.dta',
 'occ_to_naics_transition.dta',
 'foo_main.xlsx',
 'crosswalk.xlsx',
 'titles.xlsx',
 'Career_Value_by_Industry_Autom_Shock.do',
 'occ2010soc_adj.dta',
 'prob_occ_nat_industry.do',
 'Automation_and_Career_Value (5).pdf',
 'National industry specific November',
 'occ_ind_transitions_National.dta']

In [99]:
data_1 = pd.read_stata('/Users/nvarioshkin/Desktop/RA Petrova/Task 4/dc-decomp-infadj-allcz.dta')
data = pd.read_excel('/Users/nvarioshkin/Desktop/RA Petrova/Task 4/National industry specific November/natsector_november2004_dl.xls')

data = data.loc[data['GROUP'] != 'major', :]
data = data.loc[data['OCC_TITLE'] != 'Industry Total', :]
data = data.loc[:, ['NAICS', 'NAICS_TITLE', 'OCC_CODE', 'OCC_TITLE', 'TOT_EMP']]
data['OCC_CODE'] = data['OCC_CODE'].str.replace('-', '')



data_disaggr = pd.read_excel('/Users/nvarioshkin/Desktop/RA Petrova/Task 4/National industry specific November/nat3d_november2004_dl.xls')

data_disaggr = data_disaggr.loc[data_disaggr['GROUP'] != 'major', :]
data_disaggr = data_disaggr.loc[data_disaggr['OCC_TITLE'] != 'Industry Total', :]
data_disaggr = data_disaggr.loc[:, ['NAICS', 'NAICS_TITLE', 'OCC_CODE', 'OCC_TITLE', 'TOT_EMP']]
data_disaggr['OCC_CODE'] = data_disaggr['OCC_CODE'].str.replace('-', '')
data_disaggr['NAICS'] = data_disaggr['NAICS'].astype(str).str.slice(0, 2)
data_disaggr = data_disaggr.replace('**', np.nan)
data_disaggr[['TOT_EMP']] = data_disaggr[['TOT_EMP']].astype(float)
data_disaggr_1 = data_disaggr.groupby(by = ['NAICS', 'OCC_CODE'], as_index = False).sum()

x = ['31', '32', '33', '44', '45', '48', '49']

data_disaggr_1 = data_disaggr_1[data_disaggr_1['NAICS'].isin(x)]
data_disaggr_1 = data_disaggr_1.merge(data_disaggr[['OCC_CODE', 'OCC_TITLE']].drop_duplicates(), on = 'OCC_CODE', how = 'left')


data = data.replace('**', np.nan)
data.loc[:, ['TOT_EMP']] = data.loc[:, ['TOT_EMP']].astype(float)

y = ['31-33', '44-45', '48-49']
data = data[~data['NAICS'].isin(y)]

data = pd.concat([data, data_disaggr_1], axis = 0)
data = data.sort_values(['NAICS', 'OCC_CODE'])

data.loc[data['NAICS'].isin(['31', '32', '33']), 'NAICS_TITLE'] = 'Manufacturing'
data.loc[data['NAICS'].isin(['44', '45']), 'NAICS_TITLE'] = 'Retail Trade'
data.loc[data['NAICS'].isin(['48', '49']), 'NAICS_TITLE'] = 'Transportation and Warehousing'


data = data.reset_index(drop = True)
data[['NAICS', 'TOT_EMP']]  = data[['NAICS', 'TOT_EMP']].astype(float)
data = data.sort_values('OCC_CODE')

In [100]:
data.to_stata('occ_ind_NAICS_National.dta', write_index = False)

In [105]:
data[data['OCC_CODE'] == '111011']['TOT_EMP'].sum()

334990.0

In [107]:
data

,NAICS,NAICS_TITLE,OCC_CODE,OCC_TITLE,TOT_EMP
0,11.0,"Agriculture, Forestry, Fishing, and Hunting",111011,Chief executives,590.0
5988,56.0,Administrative and Support and Waste Managemen...,111011,Chief executives,19660.0
389,22.0,Utilities,111011,Chief executives,1540.0
640,23.0,Construction,111011,Chief executives,23580.0
8889,92.0,Public Administration,111011,Chief executives,26060.0
...,...,...,...,...,...
2979,44.0,Retail Trade,537199,"Material moving workers, all other",1410.0
2617,42.0,Wholesale Trade,537199,"Material moving workers, all other",2370.0
2111,33.0,Manufacturing,537199,"Material moving workers, all other",4840.0
7685,62.0,Health Care and Social Assistance,537199,"Material moving workers, all other",690.0
9520,92.0,Public Administration,537199,"Material moving workers, all other",4910.0

In [94]:
foo_main = data_1['soc1'].drop_duplicates().str.split('_', expand = True)
foo_main = foo_main.reset_index(drop = True)
foo_main['key'] = foo_main.index
foo_main = foo_main.melt(id_vars = 'key').dropna().drop(['variable'], axis = 1)
foo_main = foo_main.sort_values('value').reset_index(drop = True)
foo_main = foo_main.rename({'value' : 'OCC_CODE'}, axis = 1)
foo_main = foo_main[['OCC_CODE', 'key']] 


crosswalk = data[['OCC_CODE', 'OCC_TITLE']].drop_duplicates()
crosswalk = crosswalk.merge(foo_main, on = 'OCC_CODE',  how = 'left')
crosswalk['cross_key'] = crosswalk.index

In [95]:
def changer(string) : 
    
    length = len(string)
    
    dum = crosswalk[['OCC_CODE', 'cross_key']].copy()
    dum['OCC_CODE'] = dum['OCC_CODE'].map(lambda x : x[:-length] + string)
    dum = dum.merge(foo_main, on = 'OCC_CODE', how = 'left').drop(['OCC_CODE'], axis = 1)
    crosswalk[['cross_key', 'key']] = crosswalk[['cross_key', 'key']].fillna(dum)

In [96]:
l = ['0', '00', '000', '0000', 'X', 'XX', 'XXX', 'XXXX', 'Y', 'YY', 'YYY', 'YYYY']

for item in l : 
    changer(item)

In [98]:
foo_main2 = data_1[['soc1']].drop_duplicates().reset_index(drop = True)
foo_main2 = foo_main2.reset_index(drop = True)
foo_main2['key'] = foo_main2.index

crosswalk = crosswalk.merge(foo_main2, on = 'key', how = 'left')
crosswalk = crosswalk[['OCC_CODE', 'soc1']]
crosswalk.to_stata('crosswalk.dta', write_index = False)

In [112]:
pd.read_stata('occ_ind_transitions_National.dta')

,occsoc,ind1990,nat_occsoc_ind,nat_occsoc_tot,nat_share_empl,industry_ifr19
0,000000,n/a (not applicable),47988350.0,47988352.0,1.000000,
1,111011,"agricultural production, crops",4027.0,1272184.0,0.003165,agriculture
2,111011,"agricultural production, livestock",1335.0,1272184.0,0.001049,agriculture
3,111011,veterinary services,187.0,1272184.0,0.000147,agriculture
4,111011,landscape and horticultural services,5945.0,1272184.0,0.004673,agriculture
...,...,...,...,...,...,...
53200,559830,marines,11813.0,167274.0,0.070621,
53201,559830,coast guard,2424.0,167274.0,0.014491,
53202,559830,"armed forces, branch not specified",60900.0,167274.0,0.364073,
53203,559830,military reserves or national guard,5696.0,167274.0,0.034052,
53204,559920,last worked 1984 or earlier,1082131.0,1082131.0,1.000000,

In [113]:
pd.read_stata('/Users/nvarioshkin/Desktop/RA Petrova/Task 4/occ2010soc_adj.dta')

     occsoc                                agg_soc2010
0    311010                              311010_311011
1    291060                                     291060
2    252020                                     252020
3    439061                                     439061
4    292010                                     292010
..      ...                                        ...
597  519193  513099_519141_519192_519193_519199_5191XX
598  519199  513099_519141_519192_519193_519199_5191XX
599  536011                              536011_5360XX
600  537011                       537011_537041_5370XX
601  537199                537111_537121_537199_5371XX

[602 rows x 2 columns]

In [110]:
crosswalk

    OCC_CODE                         soc1
0     111011         111011_111031_1110XX
1     111021                       111021
2     111031         111011_111031_1110XX
3     112011                       112011
4     112021                       112020
..       ...                          ...
795   537073                       537070
796   537081                       537081
797   537111  537111_537121_537199_5371XX
798   537121  537111_537121_537199_5371XX
799   537199  537111_537121_537199_5371XX

[800 rows x 2 columns]

In [111]:
pd.read_stata('/Users/nvarioshkin/Desktop/RA Petrova/Task 4/dc-decomp-infadj-allcz.dta')

,soc1,czone,c_tot2000,c_tot2004,c_tot2008,c_tot2016,c_own_tot2000,c_own_tot2004,c_own_tot2008,c_own_tot2016,...,dc2000_2008,dc_own2000_2008,dc2004_2008,dc_own2004_2008,dc2000_2016,dc_own2000_2016,dc2004_2016,dc_own2004_2016,dc2008_2016,dc_own2008_2016
0,111011_111031_1110XX,100.0,333063.233039,327806.767809,338092.600747,320600.905348,141086.062500,133289.000000,146948.765625,139904.250000,...,5029.372238,5862.706543,10285.825555,13659.756836,-12462.321158,-1181.805908,-7205.868035,6615.244629,-17491.694331,-7044.512695
1,111021,100.0,283601.647896,287239.544485,291049.159845,284226.099031,91905.796875,97198.523438,88932.695312,103001.390625,...,7447.509201,-2973.103027,3809.617506,-8265.826172,624.448466,11095.591797,-3013.444755,5802.868164,-6823.062277,14068.694336
2,112011,100.0,274340.436927,288330.922318,268769.728476,279789.463881,90207.890625,145353.937500,79972.695312,137318.453125,...,-5570.705837,-10235.193359,-19561.189976,-65381.238281,5449.023401,47110.558594,-8541.462200,-8035.487305,11019.727512,57345.750000
3,112020,100.0,284305.055166,288765.201280,290426.489804,281317.341802,90284.617188,103441.335938,94961.601562,96628.632812,...,6121.425851,4676.978027,1661.289611,-8479.733398,-2987.720981,6344.009277,-7447.858342,-6812.702148,-9109.146839,1667.031494
4,112031,100.0,262842.823767,267479.614169,284033.748105,283621.992292,66703.632812,72853.257812,99236.945312,107673.023438,...,21190.926277,32533.316406,16554.134630,26383.689453,20779.170528,40969.394531,16142.380981,34819.769531,-411.753331,8436.080078
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
272839,537063,39400.0,249378.418981,260756.165107,253543.432327,276549.206412,55700.464844,32862.210938,47418.460938,64452.390625,...,4165.012607,-8282.003906,-7212.731146,14556.251953,27170.785575,8751.923828,15793.040841,31590.179688,23005.771261,17033.927734
272840,537064,39400.0,224401.463635,229202.147458,232746.650956,226426.810907,40037.082031,39269.953125,37534.195312,40262.863281,...,8345.184420,-2502.886719,3544.499821,-1735.760132,2025.347233,225.781738,-2775.337880,992.908203,-6319.837278,2728.668457
272841,537070,39400.0,269486.955841,269122.977622,289542.233869,288359.713691,56124.589844,53082.882812,37434.707031,36592.570312,...,20055.273979,-18689.886719,20419.253862,-15648.176758,18872.758621,-19532.019531,19236.737831,-16490.310547,-1182.515718,-842.133484
272842,537081,39400.0,262643.455014,269795.866170,262821.124469,248436.672787,89007.046875,78028.101562,80297.640625,79699.171875,...,177.668935,-8709.406250,-6974.740962,2269.540039,-14206.782242,-9307.874023,-21359.192667,1671.072021,-14384.451441,-598.468140
272843,537111_537121_537199_5371XX,39400.0,296242.767061,276305.949036,283844.055376,266218.953895,127282.437500,83474.429688,62029.031250,65686.843750,...,-12398.710463,-65253.406250,7538.106314,-21445.400391,-30023.809702,-61595.589844,-10086.995031,-17787.585938,-17625.100513,3657.814941

In [ ]:
pd.read_stata('/Users/nvarioshkin/Desktop/RA Petrova/Task 4/dc-decomp-infadj-allcz.dta')

In [ ]:
516040_516041_516042